name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv package manager (latest version)
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Execute Ruff linting check
        run: uvx ruff check

      - name: Run tests
        run: uv run pytest

      - name: Test pviz commands
        run: |
          uv run pviz analyze 99.9
          uv run pviz compare 99.9 99.95
